app:
  image: amara-app
  entrypoint: ["/usr/bin/env"]
  command: /usr/bin/python manage.py runserver 0.0.0.0:8000
  environment:
      DJANGO_SETTINGS_MODULE: dev_settings
      DJANGO_LIVE_TEST_SERVER_ADDRESS: 'localhost:8081,8090-8100,9000-9200' 
      LANG: en_US.UTF-8

  volumes:
    - .:/opt/apps/unisubs

  hostname: 'unisubs.example.com'
  ports:
    - "8000:8000"
  expose:
    - "8000:8000"
  links:
    - db
    - queue
    - cache
    - search

bash:
  image: amara-app
  # This is a bit weird because our dockerfile uses both entrypoint and
  # command, so we need to override them both.  Using /usr/bin/env as the
  # entrypoint works.
  entrypoint: ["/usr/bin/env"]
  command: /bin/bash
  environment:
      DJANGO_SETTINGS_MODULE: dev_settings

  volumes:
    - .:/opt/apps/unisubs

  hostname: 'unisubs.example.com'
  ports:
    - "8000:8000"
  expose:
    - "8000:8000"
  links:
    - db
    - queue
    - cache
    - search

sslapp:
  image: amara-app
  entrypoint: ["/usr/bin/env"]
  command: /usr/bin/python manage.py runsslserver 0.0.0.0:8000
  environment:
      DJANGO_SETTINGS_MODULE: dev_settings

  volumes:
    - .:/opt/apps/unisubs
  ports:
    - "8000:8000"
  links:
    - db
    - queue
    - cache
    - search

worker:
  image: amara-app
  entrypoint: ["/usr/bin/env"]
  command: /usr/bin/python manage.py celery worker -Q celery,feeds --scheduler=djcelery.schedulers.DatabaseScheduler --loglevel=DEBUG -B -E --settings=dev_settings
  volumes:
    - .:/opt/apps/unisubs
  links:
    - db
    - queue
    - cache
    - search

db:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: amara
    MYSQL_USER: amara
    MYSQL_PASSWORD: amara
    MYSQL_DATABASE: amara
  volumes:
    - docker-dev/mysql/conf.d/:/etc/mysql/conf.d
  ports:
    - "3306"

queue:
  image: amara/rabbitmq
  ports:
    - "5672"
    - "15672"

cache:
  image: amara/memcached
  ports:
    - "11211"

search:
  image: amara/solr
  ports:
    - "8983"
